variables:
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:3.8.4-jdk-11

stages:
  - build
  - test

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn verify -Pall-tests
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
